env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - 0
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/react-in-jsx-scope: off
