name: Merge Feature Branch

on:
  workflow_dispatch:
  push:
    branches:
      - development

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Run Prettier
        run: |
          cd client
          npm run lint:fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Run Linting
          title: Run linting
          body: |
            This pull request was created by a GitHub workflow.
            It runs Eslint to format the code.
          branch: formatting
          base: ${{ github.head_ref }}
          labels: formatting

      - name: Merge Pull Request
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge formatting
          merge-method: squash
          delete-branch: false